name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8.0.332+9
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B install --file pom.xml
  
  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8.0.332+9
        cache: 'maven'
    - name: Code report
      run:  mvn -B verify -P coverage --no-transfer-progress
    
    - uses: codecov/codecov-action@v1
      with:
        file: ./**/target/site/jacoco/jacoco.xml
        name: codecov
        
  publish-snapshot:
    needs: coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8.0.332+9
        cache: 'maven'

    - name: Publish
      run: mvn -B --no-transfer-progress deploy -DskipTests --projects dw-demo-app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
